### ISSUE TITLE
Auto-renewing wildcard certificates

### ISSUE THREAD

**Issue by cjdenio** [hack-as-a-service/api#4]
As Hack Club uses OctoDNS, automatic DNS challenges are a bit of a... challenge. They can be issued via an [auth hook](https://certbot.eff.org/docs/using.html#pre-and-post-validation-hooks).

**Comment by jasonappah** [comment]
Relevant Slack convo with a little more context: https://hackclub.slack.com/archives/C01N3B30TFB/p1629473563333400 and this FAQ answer: https://certbot.eff.org/faq#does-let-s-encrypt-issue-wildcard-certificates

**Comment by cjdenio** [comment]
I'm gonna try to write a Caddy plugin for DNSimple to do this

**Comment by cjdenio** [comment]
reference: https://caddy.community/t/how-to-use-dns-provider-modules-in-caddy-2/8148
